PLATFORM := deltalake

OSF_BUILDER_DIR := ../..

# CONFIG, KERNEL_CONFIG and COREBOOT_CONFIG are derived from CONFIGS_DIR and PLATFORM.
CONFIGS_DIR := ./configs
PATCHES_DIR := ./patches
COREBOOT_BLOBS_DIR := ./blobs

include $(OSF_BUILDER_DIR)/Makefile.inc
